SELECT TOP (1000) [ID]
      ,[Name]
      ,[Age]
      ,[Gender]
      ,[Department]
      ,[Salary]
      ,[Joining_Date]
      ,[Performance_Score]
      ,[Experience]
      ,[Status]
      ,[Location]
      ,[Session]
  FROM [Employee Data].[dbo].[Employe_Performance_dataset]
